/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package android.androidCode.pingpong;

public final class R {
    public static final class attr {
    }
    public static final class drawable {
        public static final int background2=0x7f020000;
        public static final int ball1=0x7f020001;
        public static final int ball10=0x7f020002;
        public static final int ball11=0x7f020003;
        public static final int ball12=0x7f020004;
        public static final int ball2=0x7f020005;
        public static final int ball3=0x7f020006;
        public static final int ball4=0x7f020007;
        public static final int ball5=0x7f020008;
        public static final int ball6=0x7f020009;
        public static final int ball7=0x7f02000a;
        public static final int ball8=0x7f02000b;
        public static final int ball9=0x7f02000c;
        public static final int bat=0x7f02000d;
        public static final int icon=0x7f02000e;
    }
    public static final class id {
        public static final int androng=0x7f060000;
        public static final int text=0x7f060001;
    }
    public static final class layout {
        public static final int main=0x7f030000;
    }
    public static final class raw {
        public static final int clap=0x7f040000;
        public static final int hit=0x7f040001;
        public static final int terminator=0x7f040002;
    }
    public static final class string {
        public static final int app_name=0x7f050000;
        public static final int menu_info=0x7f050007;
        public static final int menu_pause=0x7f050004;
        public static final int menu_resume=0x7f050005;
        public static final int menu_sound=0x7f050006;
        public static final int menu_start_0p=0x7f050003;
        public static final int menu_start_1p=0x7f050001;
        public static final int menu_start_2p=0x7f050002;
    }
}
