/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package test.android.app;

public final class R {


    public static final class id {
        public static final int button1=0x7f080001;
        public static final int checkBox1=0x7f080007;
        public static final int checkBox2=0x7f080008;
        public static final int radio0=0x7f080003;
        public static final int radio1=0x7f080004;
        public static final int radio2=0x7f080005;
        public static final int radioGroup1=0x7f080002;
        public static final int seekBar1=0x7f080006;
        public static final int textView1=0x7f080000;
    }
    
    public static final class layout {
        public static final int activity_main=0x7f030000;
    }
}
