/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package test.android.app;

import java.util.ArrayList;
import java.util.HashMap;

public final class R_bad {


    public static final class id {
        public static final String button1="string1";
        public static final int checkBox1=-5;        
        public static final double checkBox2=0x7f080008;
        public static final ArrayList<String> radio0=new ArrayList<String>();
        public static final HashMap<Integer, Integer> radio1 = null;

    }
    
    private static final class layout {
        public static final int activity_main=10;
    }
}
